/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1alpha1

import (
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	datastore_v1alpha1 "nicolaferraro.me/datastore-crd/pkg/apis/datastore/v1alpha1"
	versioned "nicolaferraro.me/datastore-crd/pkg/client/clientset/versioned"
	internalinterfaces "nicolaferraro.me/datastore-crd/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "nicolaferraro.me/datastore-crd/pkg/client/listers/datastore/v1alpha1"
)

// DataStoreInformer provides access to a shared informer and lister for
// DataStores.
type DataStoreInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.DataStoreLister
}

type dataStoreInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDataStoreInformer constructs a new informer for DataStore type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDataStoreInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDataStoreInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDataStoreInformer constructs a new informer for DataStore type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDataStoreInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DatastoreV1alpha1().DataStores(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DatastoreV1alpha1().DataStores(namespace).Watch(options)
			},
		},
		&datastore_v1alpha1.DataStore{},
		resyncPeriod,
		indexers,
	)
}

func (f *dataStoreInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDataStoreInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *dataStoreInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&datastore_v1alpha1.DataStore{}, f.defaultInformer)
}

func (f *dataStoreInformer) Lister() v1alpha1.DataStoreLister {
	return v1alpha1.NewDataStoreLister(f.Informer().GetIndexer())
}
